### PR TITLE
Passthru of graphviz node shape,style

### PR DESCRIPTION
**Pull request by Russtopia**
Addition of -nodeshape and -nodestyle to allow some customization of output visuals

### CODE REVIEW

**Comment by Russtopia** [comment]
Hi, I kind of forgot about this PR. Any objection to it? It just adds ability to let the user style the graph nodes.

Thanks,
-Russ

**Comment by suntong** [comment]
Bump

**Comment by Russtopia** [comment]
> Bump

Hmm, seems @ofabry is not giving attention lately to anything other than private repos according to his github activity ... if you want this feature, to grab my fork over at https://github.com/Russtopia/go-callvis/tree/node-styles for now.

Hopefully someday he'll be back to merge here :)

**Comment by ofabry** [comment]
Hey @Russtopia thanks for the PR and sorry for the delay. Work and life keeping me busy..

Could you please update the PR and pass the parameters via graph's `Options` field similarly to `minlen`. The dot template should not really have access to the raw flags anyway.

**Comment by Russtopia** [comment]
> Hey @Russtopia thanks for the PR and sorry for the delay. Work and life keeping me busy..
> 
> Could you please update the PR and pass the parameters via graph's `Options` field similarly to `minlen`. The dot template should not really have access to the raw flags anyway.

Understood :) I've updated it to use the templating as minlen does -- seems to work locally. Hope that's more in style with what you wanted!

Cheers, -R.

**Review by ondrej-fabry — APPROVED** [review]

**Pull request merged**
